version: '3.8'
services:
  backend:
    build: 
      context: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api:/api

  frontend:
    build: 
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
